In [ ]:
pip install numpy

In [ ]:
import numpy as np

def input_matrix(name="Matrix"):
    """
    Function to take input from the user for matrix creation.
    Returns the matrix as a NumPy array.
    """
    print(f"Enter the dimensions of {name} (rows, columns):")
    rows, cols = map(int, input().split())

    print(f"Enter the elements of {name} row by row:")
    elements = []
    for _ in range(rows):
        row = list(map(float, input().split()))
        elements.append(row)

    matrix = np.array(elements)
    print(f"{name} Matrix:\n", matrix)
    return matrix

def matrix_addition(matrix1, matrix2):
    if matrix1.shape == matrix2.shape:
        return matrix1 + matrix2
    else:
        print("Error: Matrices must have the same shape for addition.")
        return None

def matrix_subtraction(matrix1, matrix2):
    if matrix1.shape == matrix2.shape:
        return matrix1 - matrix2
    else:
        print("Error: Matrices must have the same shape for subtraction.")
        return None

def matrix_multiplication(matrix1, matrix2):
    if matrix1.shape[1] == matrix2.shape[0]:
        return np.dot(matrix1, matrix2)
    else:
        print("Error: Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication.")
        return None

def matrix_transpose(matrix):
    return matrix.T

def matrix_determinant(matrix):
    if matrix.shape[0] == matrix.shape[1]:  # Check if it's a square matrix
        return np.linalg.det(matrix)
    else:
        print("Error: Determinant can only be calculated for square matrices.")
        return None

def print_matrix_result(operation, result):
    if result is not None:
        print(f"{operation} Result:\n{result}\n")
    else:
        print(f"{operation} could not be performed due to an error.\n")

def main():
    print("Welcome to the Matrix Operations Tool!")

    # Get matrices from the user
    matrix1 = input_matrix("Matrix 1")
    matrix2 = input_matrix("Matrix 2")

    # Matrix Addition
    result = matrix_addition(matrix1, matrix2)
    print_matrix_result("Matrix Addition", result)

    # Matrix Subtraction
    result = matrix_subtraction(matrix1, matrix2)
    print_matrix_result("Matrix Subtraction", result)

    # Matrix Multiplication
    result = matrix_multiplication(matrix1, matrix2)
    print_matrix_result("Matrix Multiplication", result)

    # Matrix Transpose for Matrix 1
    result = matrix_transpose(matrix1)
    print_matrix_result("Matrix 1 Transpose", result)

    # Matrix Transpose for Matrix 2
    result = matrix_transpose(matrix2)
    print_matrix_result("Matrix 2 Transpose", result)

    # Matrix Determinant for Matrix 1
    result = matrix_determinant(matrix1)
    if result is not None:
        print(f"Determinant of Matrix 1: {result}")

    # Matrix Determinant for Matrix 2
    result = matrix_determinant(matrix2)
    if result is not None:
        print(f"Determinant of Matrix 2: {result}")

if __name__ == "__main__":
    main()


Welcome to the Matrix Operations Tool!
Enter the dimensions of Matrix 1 (rows, columns):
 2 2
Enter the elements of Matrix 1 row by row:
1 2
3 4 
Matrix 1 Matrix:
 [[1. 2.]
 [3. 4.]]
Enter the dimensions of Matrix 2 (rows, columns):
2 2
Enter the elements of Matrix 2 row by row:
5 6 
7 8 
Matrix 2 Matrix:
 [[5. 6.]
 [7. 8.]]
Matrix Addition Result:
[[ 6.  8.]
 [10. 12.]]

Matrix Subtraction Result:
[[-4. -4.]
 [-4. -4.]]

Matrix Multiplication Result:
[[19. 22.]
 [43. 50.]]

Matrix 1 Transpose Result:
[[1. 3.]
 [2. 4.]]

Matrix 2 Transpose Result:
[[5. 7.]
 [6. 8.]]

Determinant of Matrix 1: -2.0000000000000004
Determinant of Matrix 2: -2.000000000000005
